// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace carpark_info_assignment.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20260503080659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("CarPark", b =>
                {
                    b.Property<string>("car_park_no")
                        .HasColumnType("TEXT");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("basement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("decks")
                        .HasColumnType("INTEGER");

                    b.Property<float>("gantry_height")
                        .HasColumnType("REAL");

                    b.Property<bool>("night_parking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("short_term_end")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("short_term_start")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("x_coord")
                        .HasColumnType("REAL");

                    b.Property<float>("y_coord")
                        .HasColumnType("REAL");

                    b.HasKey("car_park_no");

                    b.ToTable("CARPARK");
                });

            modelBuilder.Entity("CarParkSys", b =>
                {
                    b.Property<int>("ParkingSystemssystem_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("system_id")
                        .HasColumnType("TEXT");

                    b.HasKey("ParkingSystemssystem_id", "system_id");

                    b.HasIndex("system_id");

                    b.ToTable("CarParkSys");
                });

            modelBuilder.Entity("CarParkTyp", b =>
                {
                    b.Property<int>("LotTypestype_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("type_id")
                        .HasColumnType("TEXT");

                    b.HasKey("LotTypestype_id", "type_id");

                    b.HasIndex("type_id");

                    b.ToTable("CarParkTyp");
                });

            modelBuilder.Entity("FreePark", b =>
                {
                    b.Property<int>("free_park_instance_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("car_park_noFPcar_park_no")
                        .HasColumnType("TEXT");

                    b.Property<int>("day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("end_time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("start_time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("free_park_instance_id");

                    b.HasIndex("car_park_noFPcar_park_no");

                    b.ToTable("FREE_PARK");
                });

            modelBuilder.Entity("Sys", b =>
                {
                    b.Property<int>("system_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("system_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("system_id");

                    b.ToTable("SYSTEM");
                });

            modelBuilder.Entity("Typ", b =>
                {
                    b.Property<int>("type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("type_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("type_id");

                    b.ToTable("TYPE");
                });

            modelBuilder.Entity("CarParkSys", b =>
                {
                    b.HasOne("Sys", null)
                        .WithMany()
                        .HasForeignKey("ParkingSystemssystem_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarPark", null)
                        .WithMany()
                        .HasForeignKey("system_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarParkTyp", b =>
                {
                    b.HasOne("Typ", null)
                        .WithMany()
                        .HasForeignKey("LotTypestype_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarPark", null)
                        .WithMany()
                        .HasForeignKey("type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FreePark", b =>
                {
                    b.HasOne("CarPark", "car_park_noFP")
                        .WithMany("FreeParkingSessions")
                        .HasForeignKey("car_park_noFPcar_park_no");

                    b.Navigation("car_park_noFP");
                });

            modelBuilder.Entity("CarPark", b =>
                {
                    b.Navigation("FreeParkingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
